// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2KOvWKG51kI0YAFT9VhngHpVOfGL_HRY',
    appId: '1:852888010719:web:85fe041261402d94ca8e6a',
    messagingSenderId: '852888010719',
    projectId: 'recipe-sharing-6e3ca',
    authDomain: 'recipe-sharing-6e3ca.firebaseapp.com',
    storageBucket: 'recipe-sharing-6e3ca.firebasestorage.app',
    measurementId: 'G-G0HYWMLVHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEn7CyxhYLxaExY61drGvBge_K2Gf9__U',
    appId: '1:852888010719:android:cfbf07dcb90c14eeca8e6a',
    messagingSenderId: '852888010719',
    projectId: 'recipe-sharing-6e3ca',
    storageBucket: 'recipe-sharing-6e3ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-V4Eoexh_89NpWiU3I5ILR6JM9wRpFiE',
    appId: '1:852888010719:ios:c6e6fd8bafb5e591ca8e6a',
    messagingSenderId: '852888010719',
    projectId: 'recipe-sharing-6e3ca',
    storageBucket: 'recipe-sharing-6e3ca.firebasestorage.app',
    iosBundleId: 'com.example.recipeSharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-V4Eoexh_89NpWiU3I5ILR6JM9wRpFiE',
    appId: '1:852888010719:ios:c6e6fd8bafb5e591ca8e6a',
    messagingSenderId: '852888010719',
    projectId: 'recipe-sharing-6e3ca',
    storageBucket: 'recipe-sharing-6e3ca.firebasestorage.app',
    iosBundleId: 'com.example.recipeSharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2KOvWKG51kI0YAFT9VhngHpVOfGL_HRY',
    appId: '1:852888010719:web:9cbf4090a0458dd8ca8e6a',
    messagingSenderId: '852888010719',
    projectId: 'recipe-sharing-6e3ca',
    authDomain: 'recipe-sharing-6e3ca.firebaseapp.com',
    storageBucket: 'recipe-sharing-6e3ca.firebasestorage.app',
    measurementId: 'G-RNE0WXC3ES',
  );
}
